### ISSUE TITLE
cross compiling libraries

### ISSUE THREAD

**Issue by amlwwalker** [davecheney/golang-crosscompile#25]
I am using you code to cross compile for arm. I am now using the libraries

> "github.com/google/gopacket"
>     "github.com/google/gopacket/layers"
>     "github.com/google/gopacket/pcap"

They are missing from the cross compiled libraries, is there a way to get it to cross compile those libraries aswell? It currently does the standard library.

I am using the Revel framework, so to do the cross compilation I am running 

`GOOS=linux GOARCH=arm revel package tcpscanner`

Thanks
Alex

**Comment by davecheney** [comment]
If those libraries are referenced by the package you are compiling, they will be compiled as well.

Can you please provide some output, along with an explanation of what you expect to see and what you actually see.

Thanks

Dave

**Comment by tutley** [comment]
I didn't submit this, but with Go 1.8.3 on Mac OS X I get this:
GOOS=linux GOARCH=amd64 go build
# repo/url/projectname
./main.go:20: undefined: pcap.Handle
./main.go:65: undefined: pcap.OpenLive

I worked around this by cloning the repo inside a CentOS virtual machine and building it there.

**Comment by davecheney** [comment]
No more issues please. This project is no longer needed
